root = "."
tmp_dir = "tmp"

[build]
  cmd = "sqlc generate && go build -o ./tmp/main ./cmd/server"
  entrypoint = "./tmp/main"
  exclude_dir = ["tmp", "node_modules", "app", "internal/database"]

[log]
  time = true
